on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]
      
jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
    - uses: danhellem/github-actions-issue-to-work-item@v2.1
      env:
        ado_organization: "brycefisherit"
        ado_project: "What The Hack Azure DevOp Team"
        ado_wit: "Product Backlog Item"
        ado_new_state: "New"
        ado_active_state: "Approved"
        ado_close_state: "Done"
        ado_bypassrules: true
